title: April 27-28, 2023
subtitle: Rethinking Print Culture, Media, Digital and Oral History as Archive, Evidence, and Method - From Africa to the World
description: Johns Hopkins University | Baltimore, MD
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

github:
  home_url: http://127.0.0.1:4000/
  program_url: http://127.0.0.1:4000/program/
  keynote_url: http://127.0.0.1:4000/keynote/
  contact_url: http://127.0.0.1:4000/contact/