title: April 27-28, 2023
subtitle: Rethinking Print Culture, Media, Digital and Oral History as Archive, Evidence, and Method From Africa to the World
description: Johns Hopkins University | Baltimore, MD
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
plugins:
#  - jekyll-remote-theme
  - jekyll-remote-theme

github:
  home_url: https://egpalazzolo.github.io/afprint
  program_url: https://egpalazzolo.github.io/afprint/program/
  keynote_url: https://egpalazzolo.github.io/afprint/keynote/
  contact_url: https://egpalazzolo.github.io/afprint/contact/